#!/usr/bin/env Rscript

library(EasyCalibrator)
library(tibble)
library(stringr)
library(purrr)
library(dplyr)

#########################################################
## Real data: preprocessing functions
#########################################################
ReformatRawCalibData <- function(d) {
  vars <- setdiff(names(d), 'year')

  # Reformat each target into a tibble with a 'year' variable
  # and a 'value' variable
  tibbles <- purrr::map_at(d, vars, ~tibble::tibble(year=d$year, value=.))

  # For each target, remove entries that are NA-valued
  purrr::map(tibbles[vars], ~dplyr::filter(., !is.na(value)))
}

#########################################################
## Real data
#########################################################
calibrationData_raw <- tibble::tibble(
  year = 2002:2008,
  populationChildren = c(10427, 10531, 10637, 10743, 10850, 10959, 11068),
  populationAdults =   c(25903, 26162, 26424, 26688, 26955, 27224, 27497),
  notifiedTBChildren = c(82, 60, 66, 69, 73, 77, 69),
  notifiedTBExperiencedAdults = c(105, 119, 130, 109, 130, 126, 137),
  notifiedTBNaiveAdults = c(172, 234, 200, 224, 216, 233, 210),
  prevalenceHIV = c(0.052, NA, NA, NA, NA, NA, NA),
  prevalenceExperiencedAdults = c(0.097, NA, NA, NA, NA, NA, NA),
  prevalenceInfectiousNaiveAdults = c(0.0051, NA, NA, NA, NA, NA, NA),
  prevalenceInfectiousExperiencedAdults = c(0.0299, NA, NA, NA, NA, NA, NA),
  prevalenceInfectiousHouseholdContacts = c(0.031, NA, NA, NA, NA, NA, NA),
  prevalenceInfectiousHouseholdContactsUnder5
                                        = c(0.10, NA, NA, NA, NA, NA, NA)
)

calibrationData <- ReformatRawCalibData(calibrationData_raw)

tar_notif_tb_children <-
  list(type='TS',
       model=c('tbTreatmentBeginChildren',
               'tbInfectious'),
             # 'populationChildren'),
       observed=calibrationData$notifiedTBChildren,
       size='model')

tar_notif_tb_exp_adults <- 
  list(type='TS',
       model=c('tbTreatmentBeginAdultsExperienced',
               'tbInfectious'),
             # 'tbTxExperiencedAdults'),
       observed=calibrationData$notifiedTBExperiencedAdults,
       size='model')

tar_notif_tb_naive_adults <-
  list(type='TS',
       model=c('tbTreatmentBeginAdultsNaive',
               'tbInfectious'),
             # 'tbTxNaiveAdults'),
       observed=calibrationData$notifiedTBNaiveAdults,
       size='model')

tar_prevalence_HIV <-
  list(type='TS',
       model=c('hivPositive', 'populationSize'),
       observed=calibrationData$prevalenceHIV,
       size=tibble(year=2002, value=1894))

tar_prev_exp_adults <-
  list(type='TS',
       model=c('tbTxExperiencedAdults', 'populationSize'),
       observed=calibrationData$prevalenceExperiencedAdults,
       size=tibble(year=2002, value=2781))

tar_prev_inf_naive_adults <-
  list(type='TS',
       model=c('tbTxNaiveInfectiousAdults', 'tbTxNaiveAdults'),
       observed=calibrationData$prevalenceInfectiousNaiveAdults,
       size=tibble(year=2002, value=3119))

tar_prev_inf_exp_adults <-
  list(type='TS',
       model=c('tbTxExperiencedInfectiousAdults', 'tbTxExperiencedAdults'),
       observed=calibrationData$prevalenceInfectiousExperiencedAdults,
       size=tibble(year=2002, value=338))

tar_prev_inf_household_contacts <-
  list(type='TS',
       model=c('activeHouseholdContacts', 'totalHouseholdContacts'),
       observed=calibrationData$prevalenceInfectiousHouseholdContacts,
       size='model')

tar_prev_inf_household_contacts_under5 <-
  list(type='TS',
       model=c('activeHouseholdContactsUnder5', 'totalHouseholdContactsUnder5'),
       observed=calibrationData$prevalenceInfectiousHouseholdContactsUnder5,
       size='model')

targets <- list(NotifiedTBChildren =        tar_notif_tb_children,
                NotifiedTBExpAdults =       tar_notif_tb_exp_adults,
                NotifiedTBNaiveAdults =     tar_notif_tb_naive_adults,
                HIVPrevalence =             tar_prevalence_HIV,
                ExperiencedAdults =         tar_prev_exp_adults,
                NaiveInfectiousAdults =     tar_prev_inf_naive_adults,
                ExpInfectiousAdults =       tar_prev_inf_exp_adults,
                ActiveHouseholdContacts   = tar_prev_inf_household_contacts,
                ActiveHouseholdContactsU5 = tar_prev_inf_household_contacts_under5)

#########################################################
## Error handling
#########################################################

tryInform <- function(code, message) {
  handleError <- function(c) {
    c$message <- paste0(c$message, "\n", '(', message, ')')
    stop(c)
  }

  tryCatch(code, error=handleError)
}

#########################################################
## Main loop
#########################################################

processLines <- function() {
  # Open 'stdin' as a file descriptor
  f <- tryInform({f <- file('stdin'); open(f); f},
                 "Could not open 'stdin' for reading")

  # Read one line at a time until EOF
  while(length(line <- readLines(f, n = 1)) > 0){
    
    # Each line should begin with a number, which is the folder name
    # containing the files to be calibrated
    runID <- stringr::str_extract(line, "^\\d+")

    # Try to go into this directory
    tryInform(setwd(runID),
              paste0("Could not open '", runID, "' as directory"))   

    # Try to calibrate the model whose results are in this directory
    msg        <- paste0("Error in calculating likelihood for '", runID, "'")
    likelihood <- tryInform(CalibrateTargets(targets, verbose=TRUE), msg) 
    
    tryInform(setwd('..'),
              paste0("Could not exit '",runID,"' after calculating likelihood"))   

    write(paste0(line, ',', as.character(likelihood), ',', names(likelihood)),
          stdout())
  }
}

#########################################################
## CLI
#########################################################
main <- function(args) {
  processLines()
}

main(commandArgs(trailingOnly=TRUE)) 
