#!/usr/bin/env bash

# Print usage information
function print_usage {
  echo "Usage:"
  echo "  RunTBABM -h"
  echo "    Print usage information and exit"
  echo "  RunTBABM -r rangefile -n num_runsheets [options]"
  echo "    Run TBABM on 'num_runsheets' runsheets from 'rangefile'"
  echo "  RunTBABM -c runsheets_file [options]"
  echo "    Run TBABM using each line of 'runsheets_file' as a rangefile"
  echo '    Note: Must set environment variable $TMPFILE for storage of'
  echo "          files containing the individual lines"
  echo
  echo "Options:"
  echo "  -b name       Name of the run. Used for naming sbatch jobs"
  echo "  -e address    Email when job is finished. To use with -q"
  # echo "  -g            Graph the output"
  echo "  -i init_size  Initial size of population. Default 31000"
  echo "  -q            Run as a batch job through sbatch"
  echo "  -t num        Number of trajectories per runsheet. Default 4"
  echo "  -m num        Number of threads per process. Default 1"
  echo "  -j num        Number of jobs. Default 2"
  echo "  -d min        Duration of job, in minutes. Only use with -q"
  echo
  echo "Note: If 'srun' is present on the system, it will be used to"
  echo "  execute the TBABM binary, even if not within the context of"
  echo "  a job allocation."
}

# See documentation of 'getopts' or 
# https://sookocheff.com/post/bash/parsing-bash-script-arguments-with-shopts/
# for more information about processing CLI arguments in Bash scripts
optstring=":hb:r:n:t:qc:e:i:gd:m:j:"

# Make sure at least one argument was supplied. $# is the number of arguments
# to the script
if [[ $# -lt 1 ]]; then
  echo "Error: Too few options" 1>&2
  exit 1;
fi

RUN_NAME="DefaultRunName"
RUNTIME="10"
RANGEFILE=""
N_RUNSHEETS=0
N_TRAJECTORIES=1
N_THREADS=1
N_JOBS=2
N_INDIVIDUALS=31000
COLLATED=false
COLLATED_FILE=""
DO_BATCH=false
DO_EMAIL=false
DO_GRAPH=false
EMAIL_ADDR=""

RUNTBABM_OPTSTRING=""

# Put the flag being processed into the variable $opt
while getopts $optstring opt; do
  case ${opt} in
    c )
      COLLATED=true; COLLATED_FILE=$OPTARG
      RUNTBABM_OPTSTRING+="-c $OPTARG "

      # Ensure that the $TMPDIR which will be used to store temporary (1-line)
      # files for model params is indeed a directory that can be written to.
      if ! [[ -d "$TMPDIR" && -w "$TMPDIR" ]]; then
        echo 'Error: -c flag but $TMPDIR was not a dir, or not writable' 1>&2
        exit 1;
      fi

      ;;
    h )
      print_usage; exit 0
      ;;
    d )
      RUNTIME=$OPTARG;
      ;;
    b )
      RUN_NAME=$OPTARG; RUNTBABM_OPTSTRING+="-b $OPTARG "
      ;;
    r )
      RANGEFILE=$OPTARG; RUNTBABM_OPTSTRING+="-r $OPTARG "
      ;;
    n )
      N_RUNSHEETS=$OPTARG; RUNTBABM_OPTSTRING+="-n $OPTARG "
      ;;
    t )
      N_TRAJECTORIES=$OPTARG; RUNTBABM_OPTSTRING+="-t $OPTARG "
      ;;
    q )
      DO_BATCH=true
      # The next line is commented so that when executed via sbatch,
      # the script will not attempt to re-run itself
      # RUNTBABM_OPTSTRING+="-q "
      ;;
    e )
      DO_EMAIL=true
      EMAIL_ADDR=$OPTARG; RUNTBABM_OPTSTRING+="-e $OPTARG "
      ;;
    i )
      N_INDIVIDUALS=$OPTARG; RUNTBABM_OPTSTRING+="-i $OPTARG "
      ;;
    # g )
    #   DO_GRAPH=false; RUNTBABM_OPTSTRING+="-g "
    #   ;;
    m )
      N_THREADS=$OPTARG; RUNTBABM_OPTSTRING+="-m $OPTARG "
      ;;
    j )
      N_JOBS=$OPTARG; RUNTBABM_OPTSTRING+="-j $OPTARG "
      ;;
    \? )
      echo "Invalid Option: -$OPTARG" 1>&2
      exit 1;
      ;;
    : )
      echo "Invalid Option: -$OPTARG requires an argument" 1>&2
      exit 1
      ;;
  esac
done

if [[ "$RANGEFILE" = "" && "$COLLATE" = "false" ]]; then
  echo "Error: Must specify rangefile if not using the '-c' flag" 1>&2
  exit 1;
fi

if [[ "$N_RUNSHEETS" = "0" && "$COLLATE" = "false" ]]; then
  echo "Error: Must specify # rangefiles when not using the '-c' flag" 1>&2
  exit 1;
fi

if [[ "$DO_BATCH" = true ]]; then
  SBATCH_OPTSTRING=""
  SBATCH_OPTSTRING+="--time=$RUNTIME "
  SBATCH_OPTSTRING+='--partition=general '
  SBATCH_OPTSTRING+="--job-name=$RUN_NAME "
  SBATCH_OPTSTRING+='--output=slurm.log '
  SBATCH_OPTSTRING+="--ntasks=$((N_JOBS+1)) " # Extra job is for this script
  SBATCH_OPTSTRING+="--cpus-per-task=$N_THREADS "
  SBATCH_OPTSTRING+='--mem-per-cpu=750M ' # Approximate, could use tuning

  if [[ "$DO_EMAIL" = true ]]; then
    SBATCH_OPTSTRING+='--mail-type=ALL '
    SBATCH_OPTSTRING+="--mail-user=$EMAIL_ADDR"
  fi

  which sbatch > /dev/null || \
    { (>&2 echo 'Error: Batch job requested, but sbatch was not found in $PATH; exiting');\
      exit 1; }

  # Schedule the job and exit
  sbatch $SBATCH_OPTSTRING $BASH_SOURCE $RUNTBABM_OPTSTRING
  exit $?
fi

# Load dependencies: use Lmod if in cluster environment
if module help > /dev/null 2>&1; then
  module load foss/2018b || \
    { (>&2 echo 'Loading foss/2018b failed; exiting'); exit $E_RUNERR; };
  module load parallel || \
    { (>&2 echo 'Loading parallel failed; exiting');   exit $E_RUNERR; };
fi

# Ensure that GNU parallel exists, else exit
which parallel > /dev/null || \
  { (>&2 echo '"parallel" not found in $PATH; exiting'); exit $E_RUNERR; };

# Make sure that all of the RunSheets exist
if [[ "$COLLATE" = "false" ]]; then
  if ! seq -w $N_RUNSHEETS | parallel -X stat {}.json > /dev/null; then
    echo "Could not stat 1 or more of the runsheets; exiting";
    exit 1;
  fi
fi

srun="";
if which 'srun' > /dev/null; then
  # This specifies the options used to run srun. The "-N1 -n1" options are
  # used to allocates a single core to each task (a task is one model run,
  # which may include multiple trajectories).
  srun="srun -N1 -n1 --cpus-per-task $N_THREADS --exclusive";
fi

# Remove existing result directories that would conflict with the ones that
# must be created for the results that will be generated
if [[ "$COLLATE" = "false" ]]; then
  seq -w $N_RUNSHEETS | xargs rm -rf || \
    { (>&2 echo "Failed to remove existing result directories; exiting");
      exit $?; }
  seq -w $N_RUNSHEETS | xargs mkdir || \
    { (>&2 echo "Creation of an output directory failed; exiting"); exit $?; }
fi

# Determine which TBABM binary will be used. Any TBABM binary in the working
# directory is chosen first. Then, TBABM is searched for in $PATH.
if stat TBABM > /dev/null 2>&1; then
  TBABM_BIN="./TBABM";
else
  TBABM_BIN="TBABM"
fi

# Build the string of options passed to the TBABM binary. Escape (using '') 
# variables whose values should be resolved on binary invocation.
TBABM_OPTSTRING=""
TBABM_OPTSTRING+="-t $N_TRAJECTORIES "
TBABM_OPTSTRING+="-n $N_INDIVIDUALS "
TBABM_OPTSTRING+='-p {}.json '
TBABM_OPTSTRING+='-s $RANDOM '
TBABM_OPTSTRING+='-o {#}/ '
TBABM_OPTSTRING+="-m $N_THREADS "
TBABM_OPTSTRING+='-h household_structure.csv'

# Final string to use with Parallel
tbabm="$TBABM_BIN $TBABM_OPTSTRING"

# This specifies the options used to run GNU parallel:
#
#   --delay of 0.2 prevents overloading the controlling node.
#
#   -j is the number of tasks run simultaneously.
#
#   The combination of --joblog and --resume create a task log that
#   can be used to monitor progress.
#
ps_opts="-j $N_JOBS --delay 0.2 --joblog parallel.log"
pc_opts="$ps_opts --pipe --cat -N1 --tmpdir $TMPDIR" 

function tbabm_coll () {
  PARAMFILE=$1
  RUNNUM=$2
  SEED=$3

  mkdir $RUNNUM

  TBABM_OPTS="-t $N_TRAJECTORIES -n $N_INDIVIDUALS -p $PARAMFILE -s $SEED -o $RUNNUM/ -m $N_THREADS -h household_structure.csv"

  $srun $TBABM_BIN $TBABM_OPTS > $RUNNUM/stdout.txt 2> $RUNNUM/stderr.txt

  echo "$RUNNUM,$SEED"
}

export N_TRAJECTORIES N_INDIVIDUALS N_THREADS srun TBABM_BIN
export -f tbabm_coll

if [[ "$COLLATE" = "false" ]]; then
  seq -w $N_RUNSHEETS | parallel $ps_opts $srun $tbabm '>' {}.log '2>&1;' echo {}
else
  cat "$COLLATED_FILE" |
    parallel $pc_opts tbabm_coll {} '{#}' '$RANDOM' 
fi

exit $?;
